version: '3.4'
services:

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3002:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /home/ubuntu/app/frontend/wwwroot:/app/wwwroot
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(``)"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.routers.frontend.tls=true"
      - "traefik.http.services.frontend.loadbalancer.server.port=80"
      - "traefik.http.routers.frontend.service=frontend"
    networks:
      - src_all_network

networks:
  src_all_network:
    external: true
