import DefaultImage from 'assets/images/DefaultImage.webp';
interface adminNavigate {
  key: string;
  path: string;
  icon: string;
}

export const ADMIN_NAVIGATE: adminNavigate[] = [
  { key: 'dashboard', path: '/', icon: 'dashboard' },
  { key: 'users', path: '/users', icon: 'people' },
  { key: 'requests', path: '/requests', icon: 'card-list' },
  { key: 'logs', path: '/logs', icon: 'logs' },
  { key: 'translations', path: '/translations', icon: 'translations' },
];

interface IRoleInterface {
  id: number;
  text: string;
}

export const ROLE: IRoleInterface[] = [
  { id: 0, text: 'employeer' },
  { id: 1, text: 'admin' },
];

export const actions = [
  { id: 0, text: 'Login' },
  { id: 1, text: 'CreateAccount' },
  { id: 2, text: 'ChangeTaskStatus' },
  { id: 3, text: 'Report' },
  { id: 4, text: 'UpdateTranslation' },
  { id: 5, text: 'UpdateUser' },
  { id: 6, text: 'UpdateCompanyInformation' },
];

export const defaultImageUrl = DefaultImage;

export const requestArray = [
  {
    구분: -2,
    CreatedAt: '21.02.2023',
    InquiryType: '대표전화유선문의',
    CompanyName: '㈜더테스트',
    Department: 'EST실',
    ResponsiblePerson: '홍성욱',
    InquiryField: '테스팅 서비스 ',
    ClientCompany: 'LG Display',
    ProjectDescription: '투명 OLED 제품 Board H/W, S/W QA',
    Client: '이정대 책임',
    ContactNumber: '010-2605-7245',
    Email: 'wjdeohi@lgdisplay.com',
    ResponseStatus: '견적서 제출',
    FinalResult: '프로젝트 거절',
    Notes: '테셀 인원 지원받아 진행하고 계약은 더테스트로 진행 협의',
  },
  {
    구분: -1,
    CreatedAt: '01.12.2022',
    InquiryType: '사업연계',
    CompanyName: '㈜더테스트',
    Department: 'EST실',
    ResponsiblePerson: '홍성욱',
    InquiryField: '테스팅 서비스 ',
    ClientCompany: 'LGE VS사업부',
    ProjectDescription: 'Cluster CID SW Qualification Test 수행',
    Client: '조용희 선임',
    ContactNumber: '010-7707-5881',
    Email: 'yonghee.cho@lge.com',
    ResponseStatus: '긴급일정으로 거절',
    FinalResult: '프로젝트 거절',
    Notes: null,
  },
  {
    구분: 0,
    CreatedAt: '09.01.2023',
    InquiryType: '대표전화유선문의',
    CompanyName: '㈜더테스트',
    Department: 'EST실',
    ResponsiblePerson: '홍성욱',
    InquiryField: '테스팅 서비스 ',
    ClientCompany: '카네비오토모티브',
    ProjectDescription: 'Car Audio 제품 인증 검증',
    Client: '이미화',
    ContactNumber: '-',
    Email: 'mh.lee@kanavi-auto.com',
    ResponseStatus: 'Mail 견적제안 후 회신 없음',
    FinalResult: '프로젝트 거절',
    Notes:
      '와이즈스톤티에서 이관 / 초기 대응시 담당자 이관으로 지연대응, 고객사 담당자 연락처 미획득으로 상황 대응 미흡',
  },
  {
    구분: 1,
    CreatedAt: '02.01.2023',
    InquiryType: '사업연계',
    CompanyName: '㈜더테스트',
    Department: 'EST실',
    ResponsiblePerson: '홍성욱',
    InquiryField: '테스팅 서비스 ',
    ClientCompany: 'LGE HE사업부 TDD팀',
    ProjectDescription: 'LGE Smart TV QE Test',
    Client: '임정근 책임',
    ContactNumber: '010-6809-3858',
    Email: 'jeonggeun.lim@lge.com',
    ResponseStatus: '예산 편성 어려움으로 Drop처리',
    FinalResult: '프로젝트 거절',
    Notes: '`23년 계약 완료 이후 재 연락 필요성 검토 예정',
  },
  {
    구분: 2,
    CreatedAt: '01.12.2022',
    InquiryType: '사업연계',
    CompanyName: '㈜더테스트',
    Department: 'EST실',
    ResponsiblePerson: '홍성욱',
    InquiryField: '테스팅 서비스 ',
    ClientCompany: 'LGE HE사업부 TDD팀',
    ProjectDescription: 'Smart TV Normal Log 검증',
    Client: '이성진 책임',
    ContactNumber: '010-2313-0110',
    Email: 'seongjin.lee@lge.com',
    ResponseStatus: 'NLQE팀 프로젝트 진행',
    FinalResult: '수주',
    Notes: '업무진행은 LG TDD팀에서 진행하고 계약은 HE서비스기획부서에서 집행',
  },
  {
    구분: 3,
    CreatedAt: '13.02.2023',
    InquiryType: '사업연계',
    CompanyName: '㈜더테스트',
    Department: 'EST실',
    ResponsiblePerson: '홍성욱',
    InquiryField: '테스팅 서비스 ',
    ClientCompany: 'LGE 플랫폼 사업센터',
    ProjectDescription: 'LGE ThinQ App TV 연동 QE Test',
    Client: '김고은 팀장',
    ContactNumber: '010-6312-4385',
    Email: 'ge.kim@lge.com',
    ResponseStatus: 'LGE Bidding 탈락이후 Drop',
    FinalResult: '프로젝트 거절',
    Notes: '`23년 계약 이후 연락하여 진행 여부 확인 필요 / bidding 탈락이후 미진행 종료',
  },
  {
    구분: 4,
    CreatedAt: '10.05.2023',
    InquiryType: '대표전화유선문의',
    CompanyName: '㈜더테스트',
    Department: 'EST실',
    ResponsiblePerson: '홍성욱',
    InquiryField: '테스팅 서비스 ',
    ClientCompany: '슈프리마',
    ProjectDescription: '출입보안제품 FW 기능 검증',
    Client: '김광태 수석',
    ContactNumber: '031-710-2404',
    Email: 'ktkim@suprema.co.kr',
    ResponseStatus: '자체QA 활용으로 계획변경되어 Drop',
    FinalResult: '프로젝트 거절',
    Notes: '테셀 인원 지원받아 진행하고 계약은 더테스트로 진행 협의',
  },
  {
    구분: 5,
    CreatedAt: '30.05.2023',
    InquiryType: '그룹사이관(와이즈스톤티)',
    CompanyName: '㈜더테스트',
    Department: 'EST실',
    ResponsiblePerson: '홍성욱',
    InquiryField: '테스팅 서비스 ',
    ClientCompany: '커머스타',
    ProjectDescription: '슈핑앱 기능테스트 (이커머스 마트상품주문)',
    Client: '강창한 대표',
    ContactNumber: '010-6676-6225',
    Email: 'kay@commerstar.com',
    ResponseStatus: '예산 편성 어려움으로 Drop처리',
    FinalResult: '프로젝트 거절',
    Notes: '테셀 인원 지원받아 진행하고 계약은 더테스트로 진행 협의',
  },
  {
    구분: 6,
    CreatedAt: '04.06.2023',
    InquiryType: '세일즈계정(와이즈스톤)',
    CompanyName: '㈜더테스트',
    Department: 'EST실',
    ResponsiblePerson: '홍성욱',
    InquiryField: '테스팅 서비스 ',
    ClientCompany: '아스트론시큐리티',
    ProjectDescription: '아스트론시큐리티 CWS 기능테스트',
    Client: '이진주 과장',
    ContactNumber: '010-4335-5359',
    Email: 'jinju.lee@astronsec.com',
    ResponseStatus: '프로젝트 시작',
    FinalResult: '수주',
    Notes: '테셀 인원 지원받아 진행하고 계약은 더테스트로 진행 협의 (최윤석 선임, 정유나 연구원)',
  },
  {
    구분: 7,
    CreatedAt: '19.07.2023',
    InquiryType: '세일즈계정',
    CompanyName: '㈜더테스트',
    Department: 'EST실',
    ResponsiblePerson: '홍성욱',
    InquiryField: '테스팅 서비스 ',
    ClientCompany: '㈜스마트스코어',
    ProjectDescription: '골프장매니지먼트시스템(ERP) 개발 QA',
    Client: '윤상혁 매니저',
    ContactNumber: '010-7762-4452',
    Email: 'kguy44@smartscore.kr',
    ResponseStatus: '전략적 견적서 제출',
    FinalResult: '프로젝트 거절',
    Notes: '와이즈스톤티에서 진행 협의 완료된 상황에서 타사 정보 입수 목적으로 견적의뢰한 건임',
  },
  {
    구분: 8,
    CreatedAt: '18.07.2023',
    InquiryType: '세일즈계정',
    CompanyName: '㈜더테스트',
    Department: 'EST실',
    ResponsiblePerson: '홍성욱',
    InquiryField: '테스팅 서비스 ',
    ClientCompany: 'LG헬로비전',
    ProjectDescription: '제철장터 쇼핑몰 앱/웹 테스트',
    Client: '손상식',
    ContactNumber: '010-6602-4554',
    Email: 'nison@lghv.net',
    ResponseStatus: '견적서 제출/ 고객사 Drop',
    FinalResult: '프로젝트 거절',
    Notes: '고객사 내부적으로 QA진행 지연으로 Drop',
  },
  {
    구분: 9,
    CreatedAt: '14.08.2023',
    InquiryType: '세일즈계정',
    CompanyName: '㈜더테스트',
    Department: 'EST실',
    ResponsiblePerson: '홍성욱',
    InquiryField: '테스팅 서비스 ',
    ClientCompany: '주식회사 위븐',
    ProjectDescription: '웹사이트 개설 플랫폼 SW검증',
    Client: '조재웅 팀장',
    ContactNumber: '010-3354-1114',
    Email: 'cju@weven.kr',
    ResponseStatus: '견적서 제출 / 수행인원 부족으로 Drop',
    FinalResult: '프로젝트 거절',
    Notes: '와이즈스톤 그룹사 수행 지원 인원 부족으로 정중한 거절',
  },
  {
    구분: 10,
    CreatedAt: '05.09.2023',
    InquiryType: '세일즈계정',
    CompanyName: '㈜더테스트',
    Department: 'EST실',
    ResponsiblePerson: '홍성욱',
    InquiryField: '테스팅 서비스 ',
    ClientCompany: '벙커키즈',
    ProjectDescription: '마이쉽단 웹앱 SW검증',
    Client: '손준혁 이사',
    ContactNumber: '010-6574-4115',
    Email: 't35114105@bunkerkids.net',
    ResponseStatus: '사전 미팅 진행 / 고객사 내부 검토결과 예산없음으로 진행 불가',
    FinalResult: '프로젝트 거절',
    Notes: null,
  },
  {
    구분: 11,
    CreatedAt: '22.09.2023',
    InquiryType: '세일즈계정',
    CompanyName: '㈜더테스트',
    Department: 'EST실',
    ResponsiblePerson: '홍성욱',
    InquiryField: '시험성적서',
    ClientCompany: '블록웨이브랩스',
    ProjectDescription: '웹앱 SW 검증 문의',
    Client: '박오름',
    ContactNumber: '010-4443-1815',
    Email: 'ormis815@blockwavelabs.io',
    ResponseStatus: '테셀 이관',
    FinalResult: '프로젝트 이관',
    Notes: '정부 지원금 신청을 위한 3자테스트 결과 요청. 테셀 이관',
  },
  {
    구분: 12,
    CreatedAt: '02.11.2023',
    InquiryType: '세일즈계정',
    CompanyName: '㈜더테스트',
    Department: 'EST실',
    ResponsiblePerson: '홍성욱',
    InquiryField: '데이터품질관리 솔루션 문의',
    ClientCompany: '한국아이티컨설팅',
    ProjectDescription: '데이터품질관련 문의',
    Client: '김시현',
    ContactNumber: '010-7340-2567',
    Email: 'kimsihyun334@gmail.com',
    ResponseStatus: '테셀 이관',
    FinalResult: '프로젝트 이관',
    Notes: '데이터 품질 관리 솔루션 관련 문의로 테셀 이관',
  },
  {
    구분: 13,
    CreatedAt: '06.11.2023',
    InquiryType: '세일즈계정',
    CompanyName: '㈜더테스트',
    Department: 'EST실',
    ResponsiblePerson: '홍성욱',
    InquiryField: '테스팅 서비스 ',
    ClientCompany: '우아한형제들',
    ProjectDescription: '배달의민족 QA용역',
    Client: '윤세원',
    ContactNumber: '010-7607-0490',
    Email: 'yoon.ooo@woowahan.com',
    ResponseStatus: '견적서 제출',
    FinalResult: '프로젝트 거절',
    Notes: '와이즈스톤티에서 진행하고 있으나 추가적인 수행 업체 모집 중',
  },
  {
    구분: 14,
    CreatedAt: '09.11.2023',
    InquiryType: '세일즈계정',
    CompanyName: '㈜더테스트',
    Department: 'EST실',
    ResponsiblePerson: '홍성욱',
    InquiryField: '테스팅 서비스 ',
    ClientCompany: '월급쟁이부자들',
    ProjectDescription: '월부닷컴 QA',
    Client: '성주엽',
    ContactNumber: '010-8242-1956',
    Email: 'taylor@weolbu.com',
    ResponseStatus: '견적서 제출/ 고객사 Drop',
    FinalResult: '프로젝트 거절',
    Notes: null,
  },
  {
    구분: 15,
    CreatedAt: '15.11.2023',
    InquiryType: '세일즈계정',
    CompanyName: '㈜더테스트',
    Department: 'EST실',
    ResponsiblePerson: '홍성욱',
    InquiryField: '테스팅 서비스 ',
    ClientCompany: '메이저월드㈜',
    ProjectDescription: '커머스 SW 테스트 문의',
    Client: '이나나',
    ContactNumber: '010-9184-4850',
    Email: 'nnlee@mwd.kr',
    ResponseStatus: '견적서 제출/ 고객사 Drop',
    FinalResult: '프로젝트 거절',
    Notes: null,
  },
  {
    구분: 16,
    CreatedAt: '16.11.2023',
    InquiryType: '세일즈계정',
    CompanyName: '㈜더테스트',
    Department: 'EST실',
    ResponsiblePerson: '홍성욱',
    InquiryField: '테스팅 서비스 ',
    ClientCompany: '크레신㈜',
    ProjectDescription: '크레신 ODDICT App 검증',
    Client: '김문수',
    ContactNumber: '010-2735-5961',
    Email: 'moonsoo@cresyn.com',
    ResponseStatus: 'HTF팀 진행',
    FinalResult: '수주',
    Notes: '추가 계약 논의 중',
  },
  {
    구분: 17,
    CreatedAt: '29.11.2023',
    InquiryType: '세일즈계정',
    CompanyName: '㈜더테스트',
    Department: 'EST실',
    ResponsiblePerson: '홍성욱',
    InquiryField: '테스팅 서비스 ',
    ClientCompany: 'TOM TOM',
    ProjectDescription: '네비게이션 App 실차테스트',
    Client: '유태양',
    ContactNumber: '010-8899-8464',
    Email: 'taeyang.yoo@tomtom.com',
    ResponseStatus: '본계약 체결 완료',
    FinalResult: '종료후 재계약예정',
    Notes: '차년도 계약 진행중',
  },
  {
    구분: 18,
    CreatedAt: '06.12.2023',
    InquiryType: '세일즈계정',
    CompanyName: '㈜더테스트',
    Department: 'EST실',
    ResponsiblePerson: '홍성욱',
    InquiryField: '시험성적서',
    ClientCompany: '스펙터',
    ProjectDescription: 'R&D 정부과제의 개발 결과물에 대한 전문기관 인증',
    Client: '김주영',
    ContactNumber: '010-7464-1905',
    Email: ' juyoung.kim@specter.co.kr',
    ResponseStatus: '테셀 이관',
    FinalResult: '프로젝트 이관',
    Notes: '정부 지원금 신청을 위한 3자테스트 결과 요청. 테셀 이관',
  },
  {
    구분: 19,
    CreatedAt: '11.12.2023',
    InquiryType: '대표전화유선문의',
    CompanyName: '㈜더테스트',
    Department: 'EST실',
    ResponsiblePerson: '홍성욱',
    InquiryField: '테스팅 서비스 ',
    ClientCompany: 'LS전선',
    ProjectDescription: 'MES 및 실시간 설비 모니터링 시스템에 대한 사용성 검증',
    Client: '노정민',
    ContactNumber: '010-6622-6426',
    Email: 'nohjm@lscns.com',
    ResponseStatus: '견적서 제출/ 고객사 Drop',
    FinalResult: '프로젝트 거절',
    Notes: '계약 하는 것으로 얘기 되었으나 시작 전 견적서와 결과보고서 샘플 제출 후 고객사 거절함',
  },
  {
    구분: 20,
    CreatedAt: '24.01.2024',
    InquiryType: '대표전화유선문의',
    CompanyName: '㈜더테스트',
    Department: 'EST실',
    ResponsiblePerson: '홍성욱',
    InquiryField: '테스팅 서비스 ',
    ClientCompany: 'KG에듀원',
    ProjectDescription: '교원 임용시험준비 사이트 SW QA',
    Client: '방석호 팀장',
    ContactNumber: '010-8974-5736',
    Email: 'sh73zzang@kggroup.co.kr',
    ResponseStatus: '대면미팅, 견적서제출',
    FinalResult: '프로젝트 거절',
    Notes: '고객사 Drop 단가 사유',
  },
  {
    구분: 21,
    CreatedAt: '16.02.2024',
    InquiryType: '대표전화유선문의',
    CompanyName: '㈜더테스트',
    Department: 'EST실',
    ResponsiblePerson: '홍성욱',
    InquiryField: '테스팅 서비스 ',
    ClientCompany: 'NH투자증권',
    ProjectDescription: '증권사이트 및 모바일 SW검증',
    Client: '박균배 부장',
    ContactNumber: '010-2373-2469',
    Email: 'kbpark@nhqv.com',
    ResponseStatus: '고객사 내부 사정으로 Drop',
    FinalResult: '프로젝트 거절',
    Notes: '견적서 및 자동화툴 제안, 내부적으로 타 업체 검토 후 결정 예정',
  },
  {
    구분: 22,
    CreatedAt: '23.02.2024',
    InquiryType: '세일즈계정',
    CompanyName: '㈜더테스트',
    Department: 'EST실',
    ResponsiblePerson: '홍성욱',
    InquiryField: '테스팅 서비스 ',
    ClientCompany: '온다',
    ProjectDescription: '여행 예약 사이트 허브 API검증 및 기능검증',
    Client: '양현 과장',
    ContactNumber: '010-8724-5933',
    Email: 'jake.yang@onda.me',
    ResponseStatus: '고객사 내부 사정으로 Drop',
    FinalResult: '프로젝트 거절',
    Notes: '견적서 및 자동화툴 제안, 내부적으로 타 업체 검토 후 결정 예정',
  },
  {
    구분: 23,
    CreatedAt: '13.03.2024',
    InquiryType: '세일즈계정',
    CompanyName: '㈜더테스트',
    Department: 'EST실',
    ResponsiblePerson: '홍성욱',
    InquiryField: '시험성적서',
    ClientCompany: '텐덤',
    ProjectDescription: '시험인증',
    Client: '이준혁',
    ContactNumber: '010-3854-1104',
    Email: 'junleo@tendom.co.kr',
    ResponseStatus: '테셀 이관',
    FinalResult: '프로젝트 이관',
    Notes: null,
  },
  {
    구분: 24,
    CreatedAt: '01.04.2024',
    InquiryType: '그룹사이관(와이즈스톤)',
    CompanyName: '㈜더테스트',
    Department: 'EST실',
    ResponsiblePerson: '홍성욱',
    InquiryField: '데이터품질 구축(컨소시엄)',
    ClientCompany: '(주)무하유',
    ProjectDescription: '초거대 AI 구축사업(17번. 학술논문이해데이터 1종)',
    Client: '왕일 프로',
    ContactNumber: '010-5132-3766',
    Email: 'iwang@muhayu.com',
    ResponseStatus: '제안제출, 제안발표 5월8일',
    FinalResult: '수주',
    Notes: '계약완료 및 진행 중',
  },
  {
    구분: 25,
    CreatedAt: '01.04.2024',
    InquiryType: '그룹사이관(와이즈스톤)',
    CompanyName: '㈜더테스트',
    Department: 'EST실',
    ResponsiblePerson: '홍성욱',
    InquiryField: '데이터품질 구축(컨소시엄)',
    ClientCompany: '(주)저스트컴퍼니',
    ProjectDescription: '초거대 AI 구축사업(11번. 문서생성 및 정보검색 데이터 3종)',
    Client: '이현식 이사',
    ContactNumber: '010-3312-4937',
    Email: 'hslee@justcompany.co.kr',
    ResponseStatus: '제안제출',
    FinalResult: '실주',
    Notes: '4월 16일 오전 10시 제출 마감 / 공동수급승인완료, 제안제출 및 발표 5/9 완료, 결과 실주',
  },
  {
    구분: 26,
    CreatedAt: '08.04.2024',
    InquiryType: '그룹사이관(와이즈스톤)',
    CompanyName: '㈜더테스트',
    Department: 'EST실',
    ResponsiblePerson: '홍성욱',
    InquiryField: '데이터품질 컨설팅(컨소시엄)',
    ClientCompany: 'AiTStory',
    ProjectDescription: '초거대 AI 품질컨설팅 및 체계고도화',
    Client: '마민철 수석',
    ContactNumber: '010-2800-2772',
    Email: 'dmz@aitstory.com',
    ResponseStatus: '제안제출, 제안발표 4월 29일',
    FinalResult: '수주',
    Notes: '계약완료 및 진행 중',
  },
  {
    구분: 27,
    CreatedAt: '12.04.2024',
    InquiryType: '대표전화유선문의',
    CompanyName: '㈜더테스트',
    Department: 'EST실',
    ResponsiblePerson: '홍성욱',
    InquiryField: '테스팅 서비스 ',
    ClientCompany: '라오가닉',
    ProjectDescription: '반려동물 앱 검증',
    Client: '장민지',
    ContactNumber: '010-5195-7702',
    Email: null,
    ResponseStatus: '정중한 거절',
    FinalResult: '프로젝트 거절',
    Notes: '반려동물을 키우는 40명을 2주안에 모집 어려움',
  },
  {
    구분: 28,
    CreatedAt: '12.04.2024',
    InquiryType: '대표전화유선문의',
    CompanyName: '㈜더테스트',
    Department: 'EST실',
    ResponsiblePerson: '홍성욱',
    InquiryField: '시험성적서',
    ClientCompany: '팀마파',
    ProjectDescription: '블록체인 App SW 기능 및 컨트랙트 테스트',
    Client: '백종훈',
    ContactNumber: '010-3869-3741',
    Email: null,
    ResponseStatus: '테셀 이관',
    FinalResult: '프로젝트 이관',
    Notes: null,
  },
  {
    구분: 29,
    CreatedAt: '12.04.2024',
    InquiryType: '대표전화유선문의',
    CompanyName: '㈜더테스트',
    Department: 'EST실',
    ResponsiblePerson: '홍성욱',
    InquiryField: '테스팅 서비스 ',
    ClientCompany: '애드캡슐소프트',
    ProjectDescription: '우리카드 앱/웹 SW 테스트',
    Client: '김주현이사',
    ContactNumber: '010-5744-2280',
    Email: null,
    ResponseStatus: '와이즈스톤 티 이관',
    FinalResult: '프로젝트 이관',
    Notes: '근무지 고려하여 오산 인원 수행 어려움',
  },
  {
    구분: 30,
    CreatedAt: '16.04.2024',
    InquiryType: '대표전화유선문의',
    CompanyName: '㈜더테스트',
    Department: 'EST실',
    ResponsiblePerson: '홍성욱',
    InquiryField: '테스트컨설팅',
    ClientCompany: '과학기술공제회',
    ProjectDescription: '테스트 프로세스 컨설팅',
    Client: '이동욱',
    ContactNumber: '010-5285-7519',
    Email: null,
    ResponseStatus: '테셀 이관',
    FinalResult: '프로젝트 이관',
    Notes: null,
  },
  {
    구분: 31,
    CreatedAt: '17.04.2024',
    InquiryType: '세일즈계정',
    CompanyName: '㈜더테스트',
    Department: 'EST실',
    ResponsiblePerson: '홍성욱',
    InquiryField: '테스팅 서비스 ',
    ClientCompany: '엑셈',
    ProjectDescription: 'DB모니터링 솔루션 테스트',
    Client: '김민성',
    ContactNumber: '010-9143-1420',
    Email: 'min@ex-em.com',
    ResponseStatus: '구두 확인',
    FinalResult: '프로젝트 거절',
    Notes: '내부 검토 후 사전 미팅 일정 수립예정/ 예산문제로 해외 아웃소싱 결정',
  },
  {
    구분: 32,
    CreatedAt: '19.04.2024',
    InquiryType: '세일즈계정',
    CompanyName: '㈜더테스트',
    Department: 'EST실',
    ResponsiblePerson: '홍성욱',
    InquiryField: '테스팅 서비스 ',
    ClientCompany: '모라이',
    ProjectDescription: '시뮬레이터 및 솔루션 개발 툴 테스트',
    Client: '김범식',
    ContactNumber: '010-7427-2501',
    Email: 'bskim@morai.ai',
    ResponseStatus: '견적 송부',
    FinalResult: '프로젝트 거절',
    Notes: '6월경 시작 예상/ 내부 검토 후 차주 연락 예정 (5/20일기준 2~3주 지연예정) / 연락 불가로 DROP 처리',
  },
  {
    구분: 33,
    CreatedAt: '22.04.2024',
    InquiryType: '세일즈계정',
    CompanyName: '㈜더테스트',
    Department: 'EST실',
    ResponsiblePerson: '홍성욱',
    InquiryField: '테스팅 서비스 ',
    ClientCompany: '로그인디',
    ProjectDescription: 'SNS앱 베타테스트',
    Client: '우혜진 매니저',
    ContactNumber: '010-4735-4261',
    Email: 'mkt1@logind.kr',
    ResponseStatus: '견적 송부',
    FinalResult: '프로젝트 거절',
    Notes: '내부 검토 후 사전 미팅 일정 수립예정이었으나 연락없음. Drop 처리',
  },
  {
    구분: 34,
    CreatedAt: '26.04.2024',
    InquiryType: '세일즈계정',
    CompanyName: '㈜더테스트',
    Department: 'EST실',
    ResponsiblePerson: '홍성욱',
    InquiryField: '테스팅 서비스 ',
    ClientCompany: '줌줌투어',
    ProjectDescription: '온라인 중개 플랫폼 앱/웹 테스트',
    Client: '제리 장',
    ContactNumber: '61-40-903-1817',
    Email: 'erry@zoomzoomtour.com',
    ResponseStatus: '메일 대응',
    FinalResult: '프로젝트 거절',
    Notes: '견적서 및 메일 대응 중 고객사 내부 사정으로 거절/ 고단가 사유',
  },
  {
    구분: 35,
    CreatedAt: '24.04.2024',
    InquiryType: '지인소개(대표님)',
    CompanyName: '㈜더테스트',
    Department: 'EST실',
    ResponsiblePerson: '홍성욱',
    InquiryField: '테스팅 서비스 ',
    ClientCompany: '포멀웍스',
    ProjectDescription: '고리 원자력 발전소 시스템 품질 컨설팅',
    Client: '오창균 수석',
    ContactNumber: '010-3482-4405',
    Email: 'changkyoon.oh@formalworks.com',
    ResponseStatus: '진행대기',
    FinalResult: '수주',
    Notes: '10월 추가 현장 시험 대기 중 ( ICT시험인증연구소 이관 예정 )',
  },
  {
    구분: 36,
    CreatedAt: '23.04.2024',
    InquiryType: '그룹사이관(와이즈스톤)',
    CompanyName: '㈜더테스트',
    Department: 'EST실',
    ResponsiblePerson: '홍성욱',
    InquiryField: '테스팅 서비스 ',
    ClientCompany: '㈜한국아이티컨설팅',
    ProjectDescription: '관세청 전자통관시스템 전산장비 전면교체 및 전환 사업 감리용역 AP테스트',
    Client: '이유승 이사',
    ContactNumber: '010-3449-5426',
    Email: 'yslee@itall.net',
    ResponseStatus: '견적 송부',
    FinalResult: '프로젝트 거절',
    Notes: '투입 인원 선별 중( 문승재, 엄영준, 이재명, 박의범)/ 수행일정 지연, 조율중 진행하지 않겠다는 답변',
  },
  {
    구분: 37,
    CreatedAt: '17.05.2024',
    InquiryType: '대표전화유선문의',
    CompanyName: '㈜더테스트',
    Department: 'EST실',
    ResponsiblePerson: '홍성욱',
    InquiryField: '테스팅 서비스 ',
    ClientCompany: '창업인',
    ProjectDescription: 'PC앱 기능테스트 (배달의민족과 유사앱)',
    Client: '오승철 상무',
    ContactNumber: '010-9107-3946',
    Email: 'cto@changupin.kr',
    ResponseStatus: '견적 송부',
    FinalResult: '프로젝트 거절',
    Notes: '유선 통화 후 견적송부/ 고단가 사유',
  },
  {
    구분: 38,
    CreatedAt: '13.05.2024',
    InquiryType: '세일즈계정',
    CompanyName: '㈜더테스트',
    Department: 'EST실',
    ResponsiblePerson: '홍성욱',
    InquiryField: '테스팅 서비스 ',
    ClientCompany: '한국부동산원',
    ProjectDescription: '한국부동산원 WAS서버 30대 부하테스트',
    Client: '김민우',
    ContactNumber: '010-8215-1468',
    Email: 'k26112@reb.or.kr',
    ResponseStatus: '와이즈스톤 이관',
    FinalResult: '프로젝트 이관',
    Notes: '이길영 수석 진행',
  },
  {
    구분: 39,
    CreatedAt: '16.05.2024',
    InquiryType: '세일즈계정',
    CompanyName: '㈜더테스트',
    Department: 'EST실',
    ResponsiblePerson: '홍성욱',
    InquiryField: '테스팅 서비스 ',
    ClientCompany: '스피츠에이아이',
    ProjectDescription: '전기오토바이 배터리 교환 서비스 플랫폼 테스트',
    Client: '박해룡 이사',
    ContactNumber: '010-3639-9495',
    Email: 'hypark@spitz.com',
    ResponseStatus: '대면미팅, 견적서제출 예정',
    FinalResult: null,
    Notes: '사전 미팅 완료 6/17일 / 상세 견적서 제출 완료 / 11월말 업체 선정 예정',
  },
  {
    구분: 40,
    CreatedAt: '31.05.2024',
    InquiryType: '대표전화유선문의',
    CompanyName: '㈜더테스트',
    Department: 'EST실',
    ResponsiblePerson: '홍성욱',
    InquiryField: '테스팅 서비스 ',
    ClientCompany: 'LG전자',
    ProjectDescription: 'SmartPhone App 해외결제 테스트',
    Client: '박형준',
    ContactNumber: '010-5768-6834',
    Email: 'hyoungjun40.park@lge.com',
    ResponseStatus: '유선 및 메일 대응, 정중한 거절',
    FinalResult: '프로젝트 거절',
    Notes: '해외 결제 수단 확보 및 긴급일정으로 정중한 거절',
  },
  {
    구분: 41,
    CreatedAt: '12.06.2024',
    InquiryType: '세일즈계정',
    CompanyName: '㈜더테스트',
    Department: 'EST실',
    ResponsiblePerson: '홍성욱',
    InquiryField: '테스팅 서비스 ',
    ClientCompany: '띵스파이어',
    ProjectDescription: '에너지 사용 및 배출량 모니터링 시스템 웹 플렛폼 기능/비기능(성능,보안,코드품질)테스트',
    Client: '박서은',
    ContactNumber: '010-2300-4328',
    Email: 's2tjdms@thingspire.com',
    ResponseStatus: '견적 송부',
    FinalResult: '고객사 거절',
    Notes: '비용 문제/ 더 낮은 비용의 업체 선정',
  },
  {
    구분: 42,
    CreatedAt: '18.06.2024',
    InquiryType: '세일즈계정',
    CompanyName: '㈜더테스트',
    Department: 'EST실',
    ResponsiblePerson: '홍성욱',
    InquiryField: '테스팅 서비스 ',
    ClientCompany: '애즈위메이크',
    ProjectDescription: '큐마켓 SW업데이트 정기배포 기능/비기능 테스트',
    Client: '류지원',
    ContactNumber: '010-3354-0943',
    Email: 'rgw2423@aswemake.com',
    ResponseStatus: '대면미팅, 견적서제출',
    FinalResult: '고객사 거절',
    Notes: '사전 미팅 완료 6/20일 / 샘플견적서 제출 후 대기중 // 고객사 내부 채용으로 결정함에 따른 거절',
  },
  {
    구분: 43,
    CreatedAt: '01.07.2024',
    InquiryType: '대표전화유선문의',
    CompanyName: '㈜더테스트',
    Department: 'EST실',
    ResponsiblePerson: '홍성욱',
    InquiryField: '테스팅 서비스 ',
    ClientCompany: '기업은행',
    ProjectDescription: '금융 상품 출시전 SW 검증(실제데이터기준 테스트)',
    Client: '김용주 과장',
    ContactNumber: '010-7612-9797',
    Email: null,
    ResponseStatus: '단순문의',
    FinalResult: '단순문의',
    Notes:
      '유선 대응/ 실제 고객 데이터 사용 가능 여부 문의로 테스트 데이터 활용 가능함으로 대응/ 추후 진행 필요시 연락하기로 함',
  },
  {
    구분: 44,
    CreatedAt: '02.07.2024',
    InquiryType: '지인소개(와이즈스톤 티 정창래이사 (휴맥스 이창헌 수석)',
    CompanyName: '㈜더테스트',
    Department: 'EST실',
    ResponsiblePerson: '홍성욱',
    InquiryField: '테스팅 서비스 ',
    ClientCompany: 'SK매직',
    ProjectDescription: 'New Biz 제품 SW검증',
    Client: '김문식 부장',
    ContactNumber: '010-6258-7921',
    Email: 'moonsik.kim@sk.com',
    ResponseStatus: '사업설명회 참석/ 제안서 제출 완료',
    FinalResult: '수주',
    Notes:
      '사업설명회 7/5일, 7월 11일 목요일 제안서 제출 완료/ 7/17일 우선협상대상 선정(개발프로젝트)/ 7/18일 현업 사전미팅/ 7/19일 구매부서 단가 미팅',
  },
  {
    구분: 45,
    CreatedAt: '02.07.2024',
    InquiryType: '지인소개(와이즈스톤 티 정창래이사 (휴맥스 이창헌 수석)',
    CompanyName: '㈜더테스트',
    Department: 'EST실',
    ResponsiblePerson: '홍성욱',
    InquiryField: '테스팅 서비스 ',
    ClientCompany: 'SK매직',
    ProjectDescription: '렌탈/가전 제품(정수기,공기청정기,비데) SW 운영검증',
    Client: '김문식 부장',
    ContactNumber: '010-6258-7921',
    Email: 'moonsik.kim@sk.com',
    ResponseStatus: '사업설명회 참석/ 제안서 제출 완료',
    FinalResult: '수주',
    Notes: '사업설명회 7/5일, 7월 11일 목요일 제안서 제출 완료/ 7월말 결과 발표 예정',
  },
  {
    구분: 46,
    CreatedAt: '04.07.2024',
    InquiryType: '지인소개(무하유 왕일프로)',
    CompanyName: '㈜더테스트',
    Department: 'EST실',
    ResponsiblePerson: '홍성욱',
    InquiryField: '데이터 구축 품질(컨소시엄)',
    ClientCompany: '헌법재판소 (무하유 컨소시엄)',
    ProjectDescription: '헌법재판소 판례정보 개방체계 구축 품질 /API 통합검증',
    Client: '왕일 프로',
    ContactNumber: '010-5132-3766',
    Email: 'iwang@muhayu.com',
    ResponseStatus: '와이즈스톤 ICT시험인증연구소 이관',
    FinalResult: '이관',
    Notes: '와이즈스톤 ICT시험인증연구소 이관',
  },
  {
    구분: 47,
    CreatedAt: '16.07.2024',
    InquiryType: '지인소개(홍성욱이사)',
    CompanyName: '㈜더테스트',
    Department: 'EST실',
    ResponsiblePerson: '홍성욱',
    InquiryField: '테스팅 서비스 ',
    ClientCompany: '투비소프트',
    ProjectDescription: 'SW 개발 SI 테스트 문의',
    Client: '이우철 부사장',
    ContactNumber: '010-8700-4364',
    Email: 'comnik@tobesoft.com',
    ResponseStatus: '와이즈스톤, 더테스트 회사소개서 송부',
    FinalResult: '단순문의',
    Notes: '유선 통화 후 회사소개서 송부',
  },
  {
    구분: 48,
    CreatedAt: '23.07.2024',
    InquiryType: '세일즈계정',
    CompanyName: '㈜더테스트',
    Department: 'EST실',
    ResponsiblePerson: '홍성욱',
    InquiryField: '테스팅 서비스 ',
    ClientCompany: '윤커뮤니케이션즈',
    ProjectDescription: '사업 서비스 포탈 SW 검증 문의',
    Client: '하혜정',
    ContactNumber: '010-9401-5774',
    Email: 'ring78@yooncoms.com',
    ResponseStatus: '유선 및 메일 대응, 브로슈어 송부',
    FinalResult: '고객사 수주실패',
    Notes: '테스트 절차 및 샘플 견적서 송부 // 8월4주차 입찰결과 예정 / 최종 수주 실패',
  },
  {
    구분: 49,
    CreatedAt: '23.07.2024',
    InquiryType: '세일즈계정',
    CompanyName: '㈜더테스트',
    Department: 'EST실',
    ResponsiblePerson: '홍성욱',
    InquiryField: '성능테스트',
    ClientCompany: '서울여자대학교',
    ProjectDescription: '가상 피팅룸 플랫폼 성능 테스트 문의',
    Client: '이종태',
    ContactNumber: '010-4708-0624',
    Email: 'light4u@swu.ac.kr',
    ResponseStatus: '와이즈스톤 ICT시험인증연구소 이관',
    FinalResult: '이관',
    Notes: '와이즈스톤 ICT시험인증연구소 이관',
  },
  {
    구분: 50,
    CreatedAt: '24.07.2024',
    InquiryType: '대표전화유선문의',
    CompanyName: '㈜더테스트',
    Department: 'EST실',
    ResponsiblePerson: '홍성욱',
    InquiryField: '테스팅 서비스 ',
    ClientCompany: '휴니버스',
    ProjectDescription: '보훈병원 시스템 개발 SW 테스트',
    Client: '박기태',
    ContactNumber: '010-2212-1556',
    Email: 'ktpark@huniverse.co.kr',
    ResponseStatus: '유선 및 메일 대응, 브로슈어 송부',
    FinalResult: '고객사 수주실패',
    Notes: '테스트 절차 및 샘플 견적서 송부 // 보훈병원 사업 Drop',
  },
  {
    구분: 51,
    CreatedAt: '09.08.2024',
    InquiryType: '세일즈계정',
    CompanyName: '㈜더테스트',
    Department: 'EST실',
    ResponsiblePerson: '홍성욱',
    InquiryField: '테스팅 서비스 ',
    ClientCompany: '다우기술',
    ProjectDescription: '웹 서비스 기능/사용성 테스트',
    Client: '최상열',
    ContactNumber: '010-9123-6514',
    Email: 'maru@daou.co.kr',
    ResponseStatus: '와이즈스톤 티 이관',
    FinalResult: '이관',
    Notes: '삼성생명 제안서 작업으로 인한 대응력 부족으로 와이즈스톤 티로 이관',
  },
  {
    구분: 52,
    CreatedAt: '12.08.2024',
    InquiryType: '세일즈계정',
    CompanyName: '㈜더테스트',
    Department: 'EST실',
    ResponsiblePerson: '홍성욱',
    InquiryField: '성능테스트',
    ClientCompany: '한국철도공사',
    ProjectDescription: '홈페이지(레츠코레일) 신규구축 사이트와 구축 비교 성능테스트',
    Client: '이종태',
    ContactNumber: '010-3443-0947',
    Email: 'wsi1449@korail.com',
    ResponseStatus: '와이즈스톤 ICT시험인증연구소 이관',
    FinalResult: '이관',
    Notes: '성능테스트',
  },
  {
    구분: 53,
    CreatedAt: '20.08.2024',
    InquiryType: '세일즈계정',
    CompanyName: '㈜더테스트',
    Department: 'EST실',
    ResponsiblePerson: '홍성욱',
    InquiryField: '테스팅 서비스 ',
    ClientCompany: '메디플러스솔루션',
    ProjectDescription: '의료용 모바일 어플리케이션 QA',
    Client: '송해석',
    ContactNumber: '010-7999-3081',
    Email: 'hs.song@medisolution.co.kr',
    ResponseStatus: '유선 및 메일 대응',
    FinalResult: '고객사 거절',
    Notes: '테스트 절차 및 견적서 송부// 고객사 내부 결정으로 QA 미실시 (추가개발)',
  },
  {
    구분: 54,
    CreatedAt: '27.08.2024',
    InquiryType: '재유입',
    CompanyName: '㈜더테스트',
    Department: 'EST실',
    ResponsiblePerson: '홍성욱',
    InquiryField: '테스팅 서비스 ',
    ClientCompany: '크레신',
    ProjectDescription: 'BT 이어폰 Software QA',
    Client: '김예지',
    ContactNumber: '010-9829-5113',
    Email: 'yeji@cresyn.com',
    ResponseStatus: '유선 및 메일 대응',
    FinalResult: '프로젝트 거절',
    Notes: '1명 긴급 요청으로 정중한 거절',
  },
  {
    구분: 55,
    CreatedAt: '03.09.2024',
    InquiryType: '세일즈계정',
    CompanyName: '㈜더테스트',
    Department: 'EST실',
    ResponsiblePerson: '홍성욱',
    InquiryField: '테스팅 서비스 ',
    ClientCompany: '디몬스터',
    ProjectDescription: '상담예약+쇼핑몰 반응형 웹사이트 기능 통합 테스트',
    Client: '김한솔',
    ContactNumber: '010-8206-4109',
    Email: 'hansol@metamonster.co.kr',
    ResponseStatus: '유선 및 메일 대응',
    FinalResult: '단순문의',
    Notes: '구체적인 진행 상황 문의 하였으나 답변 없음',
  },
  {
    구분: 56,
    CreatedAt: '27.09.2024',
    InquiryType: '세일즈계정',
    CompanyName: '㈜더테스트',
    Department: 'EST실',
    ResponsiblePerson: '홍성욱',
    InquiryField: '컨설팅 서비스',
    ClientCompany: 'HD현대로보틱스',
    ProjectDescription: '산업용 로봇팔 SW 검증 컨설팅 문의',
    Client: '정인환',
    ContactNumber: '010-2876-5557',
    Email: '123inani@hd.com',
    ResponseStatus: '유선 및 메일 대응',
    FinalResult: 'Holding',
    Notes:
      '컨설팅 문의로 사전 미팅(10/8일 오전 10시) / 출시일정 고려하여 금년도 수행 불가 결정(고객사)/ 차년도 1월 재 논의 예정',
  },
  {
    구분: 57,
    CreatedAt: '18.10.2024',
    InquiryType: '지인소개(SK매직김문식부장)',
    CompanyName: '㈜더테스트',
    Department: 'EST실',
    ResponsiblePerson: '홍성욱',
    InquiryField: '테스팅 서비스 ',
    ClientCompany: '에브리봇',
    ProjectDescription: '제품 SW 검증',
    Client: '박금열 차장',
    ContactNumber: 1071771317,
    Email: 'kypark@everybot.net',
    ResponseStatus: '유선 및 메일 대응',
    FinalResult: '고객사 거절',
    Notes: '고단가 사유로 고객사 거절',
  },
  {
    구분: 58,
    CreatedAt: '23.10.2024',
    InquiryType: '세일즈계정',
    CompanyName: '㈜더테스트',
    Department: 'EST실',
    ResponsiblePerson: '홍성욱',
    InquiryField: '테스팅 서비스 ',
    ClientCompany: '서연이화',
    ProjectDescription: '자량 제어기 기능 테스트 설계',
    Client: '권준영 주임',
    ContactNumber: 1029482479,
    Email: ' 210505@seoyoneh.com',
    ResponseStatus: '유선 및 메일 대응',
    FinalResult: '정중한거절',
    Notes: '견적 전달/ 초단기 시작 요청으로 정중한 거절',
  },
  {
    구분: 59,
    CreatedAt: '01.11.2024',
    InquiryType: '세일즈계정',
    CompanyName: '㈜더테스트',
    Department: 'EST실',
    ResponsiblePerson: '홍성욱',
    InquiryField: '테스팅 서비스 ',
    ClientCompany: '하마다랩스',
    ProjectDescription: '웹페이지 테스트',
    Client: '오종민',
    ContactNumber: 1033824642,
    Email: 'daniel@hamadalabs.com',
    ResponseStatus: '메일 대응',
    FinalResult: '정중한거절',
    Notes: '초단기 일정/ 견적 불일치로 정중한 거절',
  },
  {
    구분: 60,
    CreatedAt: '04.11.2024',
    InquiryType: '세일즈계정',
    CompanyName: '㈜더테스트',
    Department: 'EST실',
    ResponsiblePerson: '홍성욱',
    InquiryField: '테스팅 서비스 ',
    ClientCompany: '쇼엠',
    ProjectDescription: '성형, 미용 시술 의료 정보 앱 전체 검수- 앱(유저, 관리자), 웹 페이지',
    Client: '김하은',
    ContactNumber: '010-3360-8553',
    Email: 'produeun@gmail.com',
    ResponseStatus: '유선 및 메일 대응',
    FinalResult: '연락두절',
    Notes: '유선 및 메일대응/ 사전미팅 요청 / 연락두절로 Drop',
  },
  {
    구분: 61,
    CreatedAt: '07.11.2024',
    InquiryType: '대표전화유선문의',
    CompanyName: '㈜더테스트',
    Department: 'EST실',
    ResponsiblePerson: '홍성욱',
    InquiryField: '시큐어코딩진단',
    ClientCompany: '큐에스텍',
    ProjectDescription: '모바일앱 사이버보안 취약성 테스트',
    Client: '장준혁 과장',
    ContactNumber: 1029379137,
    Email: '-',
    ResponseStatus: '유선 대응',
    FinalResult: '연구소 이관',
    Notes: '유선 통화중 씨큐어코딩 진단 업무 파악하여 연구소 이관',
  },
  {
    구분: 62,
    CreatedAt: '19.11.2024',
    InquiryType: '대표전화유선문의',
    CompanyName: '㈜더테스트',
    Department: 'EST실',
    ResponsiblePerson: '홍성욱',
    InquiryField: '테스팅 서비스 ',
    ClientCompany: '헤익스',
    ProjectDescription: '온라인 교육 사이트 SW검증',
    Client: '박진수',
    ContactNumber: 1029379137,
    Email: 'jinsu.park@haix.co',
    ResponseStatus: '유선 대응',
    FinalResult: '정중한거절',
    Notes: '유선 및 메일대응/ 초단기 시작 일정으로 정중한 거절',
  },
  {
    구분: 63,
    CreatedAt: '25.11.2024',
    InquiryType: '세일즈계정',
    CompanyName: '㈜더테스트',
    Department: 'EST실',
    ResponsiblePerson: '홍성욱',
    InquiryField: '테스팅 서비스 ',
    ClientCompany: '한국은행',
    ProjectDescription: '송금한도관리 앱/웹 SW검증, API, 성능 테스트',
    Client: '김상윤 과장',
    ContactNumber: '02-759-4606',
    Email: 'sy.kim@bok.or.kr',
    ResponseStatus: '유선 및 메일 대응, 사전미팅',
    FinalResult: '사전미팅',
    Notes: '유선 및 메일대응, 사전미팅 // 1월 RFP 발송 및 입찰 공고 예정',
  },
  {
    구분: 64,
    CreatedAt: '26.11.2024',
    InquiryType: '지인소개(이성제 이사)',
    CompanyName: '㈜더테스트',
    Department: 'EST실',
    ResponsiblePerson: '홍성욱',
    InquiryField: '테스팅 서비스 ',
    ClientCompany: '신한은행',
    ProjectDescription: '2025년 ICT개발 품질검증 업무 도급',
    Client: '송화영 선임',
    ContactNumber: 1068225232,
    Email: 'shb_ictcont@shinhan.com',
    ResponseStatus: '유선 및 메일 대응',
    FinalResult: 'RFP검토중',
    Notes: '유선 및 메일대응/ 입찰참여의향서 송부',
  },
  {
    구분: 65,
    CreatedAt: '06.12.2024',
    InquiryType: '세일즈계정',
    CompanyName: '㈜더테스트',
    Department: 'EST실',
    ResponsiblePerson: '홍성욱',
    InquiryField: '테스팅 서비스 ',
    ClientCompany: '디지털팜',
    ProjectDescription: '난청/우울증 훈련 학습 도우미 앱 SW검증',
    Client: '이정미 연구원',
    ContactNumber: 1089181826,
    Email: '8778875@dgtpharm.com',
    ResponseStatus: '유선 및 메일 대응, 사전미팅',
    FinalResult: '사전미팅',
    Notes: '유선 및 메일대응, 12월11일 사전미팅 // 12월 13일 진행 여부 결정 예정',
  },
  {
    구분: 66,
    CreatedAt: '10.12.2024',
    InquiryType: '세일즈계정',
    CompanyName: '㈜더테스트',
    Department: 'EST실',
    ResponsiblePerson: '홍성욱',
    InquiryField: '테스팅 서비스 ',
    ClientCompany: '슈프리마',
    ProjectDescription: '출입통제 시스템 SW검증',
    Client: '변주령',
    ContactNumber: '031-710-2456',
    Email: 'bjury@suprema.co.kr',
    ResponseStatus: '유선 및 메일 대응',
    FinalResult: '정중한거절',
    Notes: '1명 긴급 요청으로 정중한 거절',
  },
  {
    구분: 67,
    CreatedAt: '29.11.2024',
    InquiryType: '세일즈계정',
    CompanyName: '㈜더테스트',
    Department: 'EST실',
    ResponsiblePerson: '홍성욱',
    InquiryField: '테스팅 서비스 ',
    ClientCompany: 'museLIVE',
    ProjectDescription: 'Quabble App SW검증',
    Client: '연지웅',
    ContactNumber: 1048033340,
    Email: 'rio.yeon@muse.live',
    ResponseStatus: '유선 및 메일 대응',
    FinalResult: '고객사 거절',
    Notes: '견적서 송부 후 연락 두절',
  },
];
